services:
  - type: web
    name: remxr42
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
